import { createContext, useContext, useState, useCallback, useEffect } from 'react';

export type Language = 'en' | 'zh';

const STORAGE_KEY = 'setss-lang';

const translations: Record<Language, Record<string, string>> = {
  en: {
    home: 'Home',
    about: 'About',
    authors: 'Authors',
    speakers: 'Speakers',
    program: 'Program',
    attend: 'Attend',
    aboutSetss: 'About SETSS',
    joinCff: 'Join CFF',
    organizingCommittee: 'Organizing Committee',
    registration: 'Registration',
    gettingThere: 'Getting There',
    accommodation: 'Accommodation',
    login: 'Login',
    register: 'Register',
    logout: 'Logout',
    search: 'Search...',
    welcomeTitle: 'Welcome to SETSS 2026',
    welcomeDesc1: 'The 8th Spring School on Engineering Trustworthy Software Systems (SETSS 2026) will be held on May 11-17, 2026 at the School of Computer and Information Science (CIS), Southwest University, Chongqing, China.',
    welcomeDesc2: 'The school offers lectures on leading-edge research in methods and tools for computer system engineering, topical talks on the history and trends of computing, and a workshop. SETSS 2026 is intended for university researchers (master\'s students, PhD students, academics) and software engineering practitioners in industry.',
    welcomeDesc3: 'Participants will gain insight into state-of-the-art software engineering methods and technological advances from both leading pioneers and outstanding young scholars in the field.',
    welcomeHighlight1: 'Cutting-edge lectures on formal methods & AI',
    welcomeHighlight2: 'World-class speakers from leading universities',
    welcomeHighlight3: '7-day intensive program with workshop',
    welcomeHighlight4: 'Beautiful campus of Southwest University',
    venueInfoTitle: 'Venue Information',
    venueAddress: 'Lecture Hall 0114, Building 25\nSchool of Computer and Information Science\nSouthwest University, Chongqing, China',
    venueDate: 'May 11 - May 17, 2026',
    visitOfficialWebsite: 'Visit Official Website →',
    swuCampusAlt: 'Southwest University',
    invitedSpeakers: 'Invited Speakers',
    speakersIntro: 'We are proud to host the following distinguished speakers (in alphabetical order of last name):',
    speakersDetail: 'For detailed information, including lecture titles, abstracts, and biographies, please visit the Speakers page.',
    speakersSubtitle: 'Distinguished Lecturers',
    speakerCourse: 'Course',
    speakerBiography: 'Biography',
    speakerAbstract: 'Abstract',
    registerNow: 'Register Now',
    registrationOpen: 'Registration is open!',
    joinUs: 'Join Us',
    regDesc1: 'Join us for an inspiring week of cutting-edge research, insightful lectures, and collaborative workshops at Southwest University, Chongqing.',
    regDesc2: 'SETSS 2026 is intended for university researchers in computer science and technology, including master\'s students, Ph.D students, academics and software engineering practitioners in industry.',
    learnMore: 'Learn More',
    contactInfoTitle: 'Contact Information',
    addressLabel: 'Address',
    addressDetail: 'School of Computer and Information Science\nSouthwest University\nNo. 2 Tiansheng Road, Beibei District\nChongqing, China 400715',
    emailLabel: 'Email',
    websiteLabel: 'Website',
    organizedBy: 'Organized by',
    organizerDetail: 'Centre for Research and Innovation in Software Engineering (RISE)\nSchool of Computer and Information Science\nSouthwest University',
    programSubtitle: '7-Day Program',
    programSchedule: 'Program Schedule',
    scheduleDay1: 'Day 1',
    scheduleDay2: 'Day 2',
    scheduleDay3: 'Day 3',
    scheduleDay4: 'Day 4',
    scheduleDay5: 'Day 5',
    scheduleDay6: 'Day 6',
    scheduleDay7: 'Day 7',
    scheduleDate1: 'May 11 (Mon)',
    scheduleDate2: 'May 12 (Tue)',
    scheduleDate3: 'May 13 (Wed)',
    scheduleDate4: 'May 14 (Thu)',
    scheduleDate5: 'May 15 (Fri)',
    scheduleDate6: 'May 16 (Sat)',
    scheduleDate7: 'May 17 (Sun)',
    eventOpening: 'Opening Session',
    eventTesting: 'Testing Online Meeting',
    eventCoffeeBreak: 'Coffee Break',
    eventLunch: 'Lunch',
    eventWorkshop: 'Workshop Session',
    eventWorkshopClosing: 'Workshop Session & Closing',
    eventSocialPrefix: 'Social Activity',
    activityHotPot: 'Hot Pot Feast',
    activityCruise: 'Chongqing Liangjiang Night Cruise',
    eventOpeningDetail: 'Welcome speeches by SWU President, Dean of CIS, and SETSS Briefing by Prof. Zhiming Liu. School Photo Taking.',
    eventTestingDetail: 'Connectivity test with Prof. Moshe Y. Vardi',
    conferenceChair: 'Conference Chair',
    backToHome: 'Back to Home',
    coursesTitle: 'Course Details',
    conferenceNameLine1: '2026 8th The Spring School on Engineering',
    conferenceNameLine2: 'Trustworthy Software Systems',
    conferenceDateLocation: 'May 11-17, 2026, Chongqing, China',
    heroDateTag: 'MAY 11-17, 2026 · CHONGQING, CHINA',
    heroSubtitle: 'The 8th Spring School on Engineering Trustworthy Software Systems',
    heroVenue: 'Southwest University, Chongqing, China',
    heroImageAlt: 'Southwest University',
    days: 'Days',
    hours: 'Hours',
    minutes: 'Minutes',
    seconds: 'Seconds',
    conferenceFullName: '2026 8th The Spring School on Engineering Trustworthy Software Systems',
    previousEditionsTitle: 'Previous Editions',
    previousEditionsDesc: 'SETSS 2026 is the 8th edition of SETSS, the Spring School on Engineering Trustworthy Software Systems. Previous editions were hosted by Southwest University in Chongqing, China and the Institute of Software in Beijing, China, then relative information can be found below.',
    edition: 'Edition',
    year: 'Year',
    material: 'Material',
    historyTimeline: 'History Timeline',
    // AuthModal
    authName: 'Name',
    authYourName: 'Your name',
    authEmail: 'Email',
    authPassword: 'Password',
    authFillRequired: 'Please fill in all required fields',
    authEnterName: 'Please enter your name',
    authNoAccount: "Don't have an account?",
    authHasAccount: 'Already have an account?',
    // Footer
    footerAboutTitle: 'About SETSS 2026',
    footerAboutDesc: 'The 8th Spring School on Engineering Trustworthy Software Systems, held May 11-17, 2026 at Southwest University, Chongqing, China.',
    quickLinks: 'Quick Links',
    footerContact: 'Contact',
    footerAddress1: 'RISE, School of CIS',
    footerAddress2: 'Southwest University',
    footerAddress3: 'Chongqing, China 400715',
    allRightsReserved: 'All rights reserved.',
    // Navigation
    previousEditions: 'Previous Editions',
    //Registeration
    registrationTitle: 'Registration',
    registrationNoticeTitle: 'Conference Notice',
    registrationTime: 'Meeting Time',
    registrationVenue: 'Meeting Venue',
    registrationMethod: 'Registration Method',
    registrationMethodOnsite: 'On-site payment',
    registrationMethodOnline: 'Online registration',
    registrationFeeCategory: 'Category',
    registrationFeeFee: 'Fee (RMB)',
    registrationFeeLectures: 'May 11 – May 15 (Mon–Fri Lectures)',
    registrationFeeWorkshop: 'May 16 – May 17 (Sat–Sun Workshop)',
    registrationFeeIncludes: 'Registration fee includes: lunch (Mon–Fri, except dinner), Wednesday hotpot banquet, and Friday two-river cruise ticket (168 RMB ticket + 50 RMB round-trip transportation).',
    bankTransferTitle: 'Bank Transfer Details',
    bankAccountName: 'Account Name',
    bankName: 'Bank',
    bankAccountNumber: 'Account Number',
    bankCode: 'Bank Code',
    bankRemittanceNote: 'Remittance Note',
    bankRemittanceNoteText: 'Please write "SETSS2026-Your Name" when transferring.',
    bankAfterPayment: 'After payment',
    bankAfterPaymentText: 'Send the transfer voucher and invoice information (title, tax ID) to liubocq@swu.edu.cn.',
    scanToRegister: 'Scan to Register',
    qrCodeAlt: 'Registration QR Code',
    scanToRegisterDesc: 'Please scan to register (or use bank transfer above)',
    otherInfoTitle: 'Other Information',
    otherInfoTravel: 'Participants are responsible for their own travel and accommodation expenses not listed above.',
    otherInfoCertificate: 'SETSS 2026 can provide a training certificate of 32 instructional hours for those in need.',
    officialWebsiteLabel: 'Official Website',
    registrationNoticeP1: 'The 8th Spring School on Engineering Trustworthy Software Systems (SETSS 2026) hosted by Southwest University will take place from May 11 to 17, 2026, at Southwest University, Chongqing, China. The school will feature a series of lectures on cutting-edge research in software systems engineering, formal methods, AI, cyber-physical systems, and digital twins, along with a dedicated workshop. Invited speakers include Turing Award laureate Prof. Joseph Sifakis (online), Prof. Moshe Y. Vardi (online), Prof. Einar Broch Johnsen, Prof. Kim Guldstrand Larsen, Prof. Bernhard Aichernig, Dr. Emily Yu, Prof. Jonathan P. Bowen, Prof. Wei Dong, Prof. Miaomiao Zhang, and other distinguished experts.',
    registrationNoticeP2: 'The program combines five days of lectures (May 11–15) and a two‑day workshop (May 16–17). Participants will have opportunities for in‑depth discussions, networking, and social events including a hotpot banquet and a two‑river cruise.',
    registrationVenueLine1: 'Lecture Hall 0114, Building 25',
    registrationVenueLine2: 'Southwest University (Beibei Campus), Chongqing, China',
    bankAccountNameValue: 'Southwest University',
    bankNameValue: 'Industrial and Commercial Bank of China (ICBC), Chongqing Chaoyang Sub‑branch',
    //transportation
    transportationTitle: 'Transportation to Southwest University (Beibei Campus)',
    transportationSubtitle: 'How to get to the conference venue',
    fromAirport: 'From Chongqing Jiangbei International Airport',
    fromChongqingbei: 'From Chongqingbei Railway Station',
    fromChongqingxi: 'From Chongqingxi Railway Station',
    fromChongqingdong: 'From Chongqingdong Railway Station',
    method: 'Method',
    route: 'Route',
    estimatedPrice: 'Estimated Price',
    estimatedTime: 'Estimated Time',
    metro: 'Metro',
    taxi: 'Taxi',
    airportMetroRoute: 'Line 10 (T3 Terminal) → Line 6 (Southwest University Station)',
    airportTaxiRoute: 'Airport → Southwest University Beibei Campus',
    chongqingbeiMetroRoute: 'Line 3 (Hongqihegou) → Line 6 (Southwest University Station)',
    chongqingbeiTaxiRoute: 'Chongqingbei → Southwest University Beibei Campus',
    chongqingxiMetroRoute: 'Loop Line (Ranjiaba) → Line 6 (Southwest University Station)',
    chongqingxiTaxiRoute: 'Chongqingxi → Southwest University Beibei Campus',
    chongqingdongMetroRoute: 'Line 6 (Chongqingdong → Southwest University Station)',
    chongqingdongTaxiRoute: 'Chongqingdong → Southwest University Beibei Campus',
    accommodationTitle: 'Recommended Hotels (Near Venue)',
    accommodationSubtitle: 'Comfortable stays within walking distance of the conference venue',
    hotelAddress: 'Address',
    hotelTel: 'Tel',
    hotelNote: 'Note',
    hotelNoteText: 'Rates are for reference only. Please confirm directly with the hotel.',
    moreOptions: 'More accommodation options can be found on travel platforms.',
    earlyBooking: 'Early booking is recommended.',
    ningdengHotel: 'Ningdeng Hotel',
    ningdengAddress: 'Near No. 127 Wenxingwan, Beibei District (approx. 100m from venue)',
    bolianhuiHotel: 'Bo Lian Hui Hotel 4.8★',
    bolianhuiAddress: 'No. 143 Tiansheng Li Street (next to Tiansheng Station, Line 6, opposite Gate 2 of SWU South Gate)',
    bluesHotel: 'Blues Boutique Hotel 4.9★',
    bluesAddress: 'No. 139-3-1 Tiansheng Li Street (above Rural Commercial Bank, 100m from Exit 1, SWU Station, Line 6)',
    boreeHotel: 'Boree Business Hotel 5.0★',
    boreeAddress: '2F, Building 8, Tiansheng Li Street (100m from Exit 1 Tiansheng Station, 200m from SWU Gate 2)',
  },
  zh: {
    home: '首页',
    about: '关于',
    authors: '作者',
    speakers: '讲者',
    program: '日程',
    attend: '参会',
    aboutSetss: '关于SETSS',
    joinCff: '加入CFF',
    organizingCommittee: '组委会',
    registration: '注册',
    gettingThere: '交通指南',
    accommodation: '住宿',
    login: '登录',
    register: '注册',
    logout: '退出',
    search: '搜索...',
    welcomeTitle: '欢迎来到 SETSS 2026',
    welcomeDesc1: '第八届可信软件系统工程春季学校（SETSS 2026）将于2026年5月11日至17日在中国重庆西南大学计算机与信息科学学院（CIS）举行。',
    welcomeDesc2: '本次学校将提供关于计算机系统工程方法和工具前沿研究的讲座、关于计算历史和趋势的专题报告以及研讨会。SETSS 2026面向计算机科学与技术领域的大学研究人员（硕士生、博士生、学者）以及工业界的软件工程从业者。',
    welcomeDesc3: '参与者将深入了解软件工程领域最先进的方法和技术进展，包括杰出先驱和优秀青年学者的最新研究成果。',
    welcomeHighlight1: '形式化方法与人工智能前沿讲座',
    welcomeHighlight2: '来自顶尖大学的世界级讲者',
    welcomeHighlight3: '为期7天的强化课程与研讨会',
    welcomeHighlight4: '西南大学美丽校园',
    venueInfoTitle: '会场信息',
    venueAddress: '第25教学楼0114报告厅\n计算机与信息科学学院 软件学院\n中国重庆西南大学',
    venueDate: '2026年5月11日 - 5月17日',
    visitOfficialWebsite: '访问官方网站 →',
    swuCampusAlt: '西南大学',
    invitedSpeakers: '特邀讲者',
    speakersIntro: '我们很荣幸邀请到以下杰出讲者（按姓氏字母顺序排列）：',
    speakersDetail: '点击讲者卡片查看详细信息，包括讲座标题、摘要和传记。',
    speakersSubtitle: '特邀讲者',
    speakerCourse: '讲座',
    speakerBiography: '个人简介',
    speakerAbstract: '摘要',
    registerNow: '立即注册',
    registrationOpen: '注册已开放！',
    joinUs: '加入我们',
    regDesc1: '加入我们，在重庆西南大学度过充满前沿研究、精彩讲座和协作研讨会的美好一周。',
    regDesc2: 'SETSS 2026面向计算机科学与技术领域的大学研究人员，包括硕士生、博士生、学者以及工业界的软件工程从业者。',
    learnMore: '了解更多',
    contactInfoTitle: '联系信息',
    addressLabel: '地址',
    addressDetail: '计算机与信息科学学院\n西南大学\n重庆市北碚区天生路2号\n中国 400715',
    emailLabel: '邮箱',
    websiteLabel: '网站',
    organizedBy: '主办方',
    organizerDetail: '软件工程研究与创新中心（RISE）\n计算机与信息科学学院\n西南大学',
    programSubtitle: '7天日程',
    programSchedule: '日程安排',
    scheduleDay1: '第一天',
    scheduleDay2: '第二天',
    scheduleDay3: '第三天',
    scheduleDay4: '第四天',
    scheduleDay5: '第五天',
    scheduleDay6: '第六天',
    scheduleDay7: '第七天',
    scheduleDate1: '5月11日（周一）',
    scheduleDate2: '5月12日（周二）',
    scheduleDate3: '5月13日（周三）',
    scheduleDate4: '5月14日（周四）',
    scheduleDate5: '5月15日（周五）',
    scheduleDate6: '5月16日（周六）',
    scheduleDate7: '5月17日（周日）',
    eventOpening: '开幕式',
    eventTesting: '在线会议测试',
    eventCoffeeBreak: '茶歇',
    eventLunch: '午餐',
    eventWorkshop: '研讨会',
    eventWorkshopClosing: '研讨会与闭幕式',
    eventSocialPrefix: '社交活动',
    activityHotPot: '火锅宴',
    activityCruise: '重庆两江夜游',
    eventOpeningDetail: '西南大学校长、计算机与信息科学学院院长致辞，刘志明教授作SETSS简介。集体合影。',
    eventTestingDetail: '与Moshe Y. Vardi教授进行在线连接测试',
    conferenceChair: '会议主席',
    backToHome: '返回首页',
    coursesTitle: '课程详情',
    conferenceNameLine1: '2026 第八届可信软件系统工程春季学校',
    conferenceNameLine2: '',
    conferenceDateLocation: '2026年5月11-17日，中国重庆',
    heroDateTag: '2026年5月11-17日 · 中国重庆',
    heroSubtitle: '第八届可信软件系统工程春季学校',
    heroVenue: '中国重庆西南大学',
    heroImageAlt: '西南大学',
    days: '天',
    hours: '时',
    minutes: '分',
    seconds: '秒',
    conferenceFullName: '2026 第八届可信软件系统工程春季学校',
    previousEditionsTitle: '往届会议',
    previousEditionsDesc: 'SETSS 2026 是可信软件系统工程春季学校（SETSS）的第八届会议。往届会议由中国重庆西南大学和中国北京软件研究所承办，相关信息如下。',
    edition: '届次',
    year: '年份',
    material: '资料',
    historyTimeline: '历史时间线',
    // AuthModal
    authName: '姓名',
    authYourName: '您的姓名',
    authEmail: '邮箱',
    authPassword: '密码',
    authFillRequired: '请填写所有必填项',
    authEnterName: '请输入您的姓名',
    authNoAccount: '还没有账号？',
    authHasAccount: '已有账号？',
    // Footer
    footerAboutTitle: '关于 SETSS 2026',
    footerAboutDesc: '第八届可信软件系统工程春季学校，2026年5月11-17日于中国重庆西南大学举行。',
    quickLinks: '快速链接',
    footerContact: '联系方式',
    footerAddress1: '软件工程研究与创新中心，计算机与信息科学学院',
    footerAddress2: '西南大学',
    footerAddress3: '中国重庆 400715',
    allRightsReserved: '版权所有。',
    // Navigation
    previousEditions: '往届会议',
    //Registeration
    registrationTitle: '会议注册',
    registrationNoticeTitle: '会议通知',
    registrationTime: '会议时间',
    registrationVenue: '会议地点',
    registrationMethod: '注册方式',
    registrationMethodOnsite: '现场缴费',
    registrationMethodOnline: '在线注册',
    registrationFeeCategory: '类别',
    registrationFeeFee: '费用（人民币）',
    registrationFeeLectures: '5月11日 – 5月15日（周一至周五讲座）',
    registrationFeeWorkshop: '5月16日 – 5月17日（周六至周日研讨会）',
    registrationFeeIncludes: '注册费包含：午餐（周一至周五，不含晚餐）、周三火锅宴、周五两江游船票（168元船票 + 50元往返交通）。',
    bankTransferTitle: '银行转账信息',
    bankAccountName: '账户名称',
    bankName: '开户银行',
    bankAccountNumber: '账号',
    bankCode: '银行代码',
    bankRemittanceNote: '汇款备注',
    bankRemittanceNoteText: '转账时请备注"SETSS2026-您的姓名"。',
    bankAfterPayment: '缴费后',
    bankAfterPaymentText: '请将转账凭证和开票信息（抬头、税号）发送至 liubocq@swu.edu.cn。',
    scanToRegister: '扫码注册',
    qrCodeAlt: '注册二维码',
    scanToRegisterDesc: '请扫码注册（或使用上方银行转账）',
    otherInfoTitle: '其他信息',
    otherInfoTravel: '以上未列出的交通和住宿费用，由参会者自行承担。',
    otherInfoCertificate: 'SETSS 2026 可为有需要的参会者提供32学时培训证明。',
    officialWebsiteLabel: '官方网站',
    registrationNoticeP1: '由西南大学承办的第八届可信软件系统工程春季学校（SETSS 2026）将于2026年5月11日至17日在中国重庆西南大学举行。本次学校将提供一系列关于软件系统工程、形式化方法、人工智能、信息物理系统和数字孪生前沿研究的讲座，以及一个专门的研讨会。特邀讲者包括图灵奖得主Joseph Sifakis教授（线上）、Moshe Y. Vardi教授（线上）、Einar Broch Johnsen教授、Kim Guldstrand Larsen教授、Bernhard Aichernig教授、Emily Yu博士、Jonathan P. Bowen教授、Wei Dong教授、Miaomiao Zhang教授等杰出专家。',
    registrationNoticeP2: '课程安排包括五天讲座（5月11日至15日）和两天研讨会（5月16日至17日）。参与者将有机会进行深入讨论、交流，并参加包括火锅宴和两江游船在内的社交活动。',
    registrationVenueLine1: '第25教学楼0114报告厅',
    registrationVenueLine2: '西南大学（北碚校区），中国重庆',
    bankAccountNameValue: '西南大学',
    bankNameValue: '中国工商银行重庆朝阳支行',
    transportationTitle: '西南大学（北碚校区）交通指南',
    transportationSubtitle: '如何到达会议地点',
    fromAirport: '从重庆江北国际机场出发',
    fromChongqingbei: '从重庆北站出发',
    fromChongqingxi: '从重庆西站出发',
    fromChongqingdong: '从重庆东站出发',
    method: '方式',
    route: '路线',
    estimatedPrice: '预估费用',
    estimatedTime: '预估时间',
    metro: '地铁',
    taxi: '出租车',
    airportMetroRoute: '10号线（T3航站楼）→ 6号线（西南大学站）',
    airportTaxiRoute: '机场 → 西南大学北碚校区',
    chongqingbeiMetroRoute: '3号线（红旗河沟）→ 6号线（西南大学站）',
    chongqingbeiTaxiRoute: '重庆北站 → 西南大学北碚校区',
    chongqingxiMetroRoute: '环线（冉家坝）→ 6号线（西南大学站）',
    chongqingxiTaxiRoute: '重庆西站 → 西南大学北碚校区',
    chongqingdongMetroRoute: '6号线（重庆东站 → 西南大学站）',
    chongqingdongTaxiRoute: '重庆东站 → 西南大学北碚校区',
    accommodationTitle: '推荐酒店（会场附近）',
    accommodationSubtitle: '会场步行范围内的舒适住宿选择',
    hotelAddress: '地址',
    hotelTel: '电话',
    hotelNote: '提示',
    hotelNoteText: '房价仅供参考，请直接向酒店确认。',
    moreOptions: '更多住宿选择可在旅游平台上查找。',
    earlyBooking: '建议提前预订。',
    ningdengHotel: '宁登酒店',
    ningdengAddress: '北碚区文星湾127号附近（距会场约100米）',
    bolianhuiHotel: '柏联汇酒店 4.8★',
    bolianhuiAddress: '天生丽街143号（地铁6号线天生站旁，西南大学南门2号门对面）',
    bluesHotel: '布鲁斯精品酒店 4.9★',
    bluesAddress: '天生丽街139-3-1号（农商行楼上，地铁6号线西南大学站1号出口100米）',
    boreeHotel: '柏瑞商务酒店 5.0★',
    boreeAddress: '天生丽街8号楼2楼（天生站1号出口100米，西南大学2号门200米）',
  },
};

interface LanguageContextType {
  lang: Language;
  t: (key: string, vars?: Record<string, string | number>) => string;
  toggleLang: () => void;
}

const LanguageContext = createContext<LanguageContextType | null>(null);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLang] = useState<Language>(() => {
    const saved = localStorage.getItem(STORAGE_KEY) as Language | null;
    if (saved === 'en' || saved === 'zh') return saved;
    const browserLang = navigator.language.toLowerCase();
    return browserLang.startsWith('zh') ? 'zh' : 'en';
  });

  useEffect(() => {
    document.documentElement.lang = lang === 'zh' ? 'zh-CN' : 'en';
    localStorage.setItem(STORAGE_KEY, lang);
  }, [lang]);

  const t = useCallback(
    (key: string, vars?: Record<string, string | number>) => {
      let text = translations[lang][key] ?? key;
      if (vars) {
        Object.entries(vars).forEach(([k, v]) => {
          text = text.replace(new RegExp(`{{\\s*${k}\\s*}}`, 'g'), String(v));
        });
      }
      return text;
    },
    [lang]
  );

  const toggleLang = useCallback(() => {
    setLang((prev) => (prev === 'en' ? 'zh' : 'en'));
  }, []);

  return (
    <LanguageContext.Provider value={{ lang, t, toggleLang }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}